package configtx

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/google/uuid"
	"golang.org/x/sys/unix"
)

// JournalPhase is deliberately limited to the two phases needed by the
// filesystem primitives. SQLite commit state is not represented here.
type JournalPhase string

const (
	PhasePrepared       JournalPhase = "prepared"
	PhaseRollbackFailed JournalPhase = "rollback_failed"
	// Descriptive aliases for callers that prefer the type name in constants.
	JournalPhasePrepared       = PhasePrepared
	JournalPhaseRollbackFailed = PhaseRollbackFailed
)

const maxInt64Value = int64(^uint64(0) >> 1)

// Journal is the complete version-one durable transaction marker. It stores
// only hashes, metadata, generations, and trusted derived basenames.
type Journal struct {
	FormatVersion       int          `json:"format_version"`
	TransactionID       string       `json:"transaction_id"`
	Phase               JournalPhase `json:"phase"`
	OldConfigHash       string       `json:"old_config_hash"`
	CandidateConfigHash string       `json:"candidate_config_hash"`
	OldGeneration       int64        `json:"old_generation"`
	CandidateGeneration int64        `json:"candidate_generation"`
	ServiceWasActive    bool         `json:"service_was_active"`
	LiveConfigMode      uint32       `json:"live_config_mode"`
	LiveConfigUID       int          `json:"live_config_uid"`
	LiveConfigGID       int          `json:"live_config_gid"`
	CandidateName       string       `json:"candidate_name"`
	BackupName          string       `json:"backup_name"`
}

func (j Journal) Validate() error {
	if j.FormatVersion != 1 {
		return ErrUnsupportedJournalVersion
	}
	if _, err := canonicalTransactionID(j.TransactionID); err != nil {
		return ErrInvalidJournal
	}
	if j.Phase != PhasePrepared && j.Phase != PhaseRollbackFailed {
		return ErrInvalidJournal
	}
	if !isLowerHexHash(j.OldConfigHash) || !isLowerHexHash(j.CandidateConfigHash) {
		return ErrInvalidJournal
	}
	if j.OldGeneration < 0 || j.OldGeneration == maxInt64Value {
		return ErrInvalidJournal
	}
	if j.CandidateGeneration != j.OldGeneration+1 {
		return ErrInvalidJournal
	}
	if j.LiveConfigMode != 0600 && j.LiveConfigMode != 0640 {
		return ErrInvalidJournal
	}
	if j.LiveConfigUID < 0 || j.LiveConfigGID < 0 {
		return ErrInvalidJournal
	}
	candidateName, err := derivedCandidateName(j.TransactionID)
	if err != nil || j.CandidateName != candidateName {
		return ErrInvalidJournal
	}
	backupName, err := derivedBackupName(j.TransactionID)
	if err != nil || j.BackupName != backupName {
		return ErrInvalidJournal
	}
	return nil
}

// NewTransactionID creates the only kind of transaction identifier accepted
// by this package: a canonical lowercase UUID v4 generated by trusted code.
func NewTransactionID() string {
	return uuid.New().String()
}

// NewJournal constructs a validated prepared marker for a trusted operation.
func NewJournal(transactionID, oldHash, candidateHash string, oldGeneration int64, serviceWasActive bool, metadata FileMetadata) (Journal, error) {
	if oldGeneration < 0 || oldGeneration == maxInt64Value {
		return Journal{}, ErrInvalidJournal
	}
	candidateName, err := derivedCandidateName(transactionID)
	if err != nil {
		return Journal{}, ErrInvalidJournal
	}
	backupName, err := derivedBackupName(transactionID)
	if err != nil {
		return Journal{}, ErrInvalidJournal
	}
	journal := Journal{
		FormatVersion:       1,
		TransactionID:       transactionID,
		Phase:               PhasePrepared,
		OldConfigHash:       oldHash,
		CandidateConfigHash: candidateHash,
		OldGeneration:       oldGeneration,
		CandidateGeneration: oldGeneration + 1,
		ServiceWasActive:    serviceWasActive,
		LiveConfigMode:      metadata.Mode,
		LiveConfigUID:       metadata.UID,
		LiveConfigGID:       metadata.GID,
		CandidateName:       candidateName,
		BackupName:          backupName,
	}
	if err := journal.Validate(); err != nil {
		return Journal{}, err
	}
	return journal, nil
}

func marshalJournal(journal Journal) ([]byte, error) {
	if err := journal.Validate(); err != nil {
		return nil, err
	}
	encoded, err := json.Marshal(journal)
	if err != nil {
		return nil, fmt.Errorf("marshal transaction journal: %w", err)
	}
	if len(encoded) > MaxJournalBytes {
		return nil, ErrMalformedJournal
	}
	return encoded, nil
}

func (g *LockGuard) CreatePreparedJournal(journal Journal) error {
	done, err := g.beginOperation()
	if err != nil {
		return err
	}
	defer done()
	if journal.Phase != PhasePrepared {
		return ErrInvalidJournal
	}
	if err := journal.Validate(); err != nil {
		return err
	}
	if err := ensureTransactionDirectories(g.layout); err != nil {
		return err
	}
	if err := checkJournalDestination(g.layout.JournalPath, false); err != nil {
		return err
	}
	encoded, err := marshalJournal(journal)
	if err != nil {
		return err
	}
	return g.writeNewJournal(encoded, journal.TransactionID)
}

func (g *LockGuard) writeNewJournal(encoded []byte, transactionID string) error {
	tempPath, file, err := g.openJournalTemp(transactionID)
	if err != nil {
		return err
	}
	keepTemp := true
	defer func() {
		if keepTemp {
			_ = os.Remove(tempPath)
		}
	}()
	if err := writeAll(file, encoded); err != nil {
		_ = file.Close()
		return fmt.Errorf("write transaction journal: %w", err)
	}
	if err := fsyncAndClose(file); err != nil {
		return fmt.Errorf("sync transaction journal: %w", err)
	}
	if err := checkJournalDestination(g.layout.JournalPath, false); err != nil {
		return err
	}
	if err := os.Rename(tempPath, g.layout.JournalPath); err != nil {
		return fmt.Errorf("write transaction journal atomically: %w", err)
	}
	keepTemp = false
	if err := fsyncDirectory(g.layout.StateDir); err != nil {
		return fmt.Errorf("sync transaction state directory: %w", err)
	}
	return nil
}

func (g *LockGuard) openJournalTemp(transactionID string) (string, *os.File, error) {
	if _, err := canonicalTransactionID(transactionID); err != nil {
		return "", nil, ErrInvalidJournal
	}
	for attempt := 0; attempt < 16; attempt++ {
		suffix, err := randomSuffix()
		if err != nil {
			return "", nil, fmt.Errorf("generate journal temporary name: %w", err)
		}
		path := filepath.Join(g.layout.StateDir, ".subbox-journal-"+transactionID+"-"+suffix+".tmp")
		file, err := openNewArtifact(path, 0600)
		if err == nil {
			return path, file, nil
		}
		if errors.Is(err, ErrArtifactExists) {
			continue
		}
		return "", nil, err
	}
	return "", nil, ErrArtifactExists
}

func checkJournalDestination(path string, requireExisting bool) error {
	info, err := os.Lstat(path)
	if os.IsNotExist(err) {
		if requireExisting {
			return ErrJournalNotFound
		}
		return nil
	}
	if err != nil {
		return fmt.Errorf("inspect transaction journal: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return ErrUnsafeFile
	}
	if !info.Mode().IsRegular() {
		return ErrUnsafeFile
	}
	if info.Mode().Perm() != 0600 {
		return ErrUnsafePermissions
	}
	if !requireExisting {
		return ErrJournalExists
	}
	return nil
}

func (g *LockGuard) ReadJournal() (Journal, error) {
	done, err := g.beginOperation()
	if err != nil {
		return Journal{}, err
	}
	defer done()
	return g.readJournalLocked()
}

func (g *LockGuard) readJournalLocked() (Journal, error) {
	if err := ensureTransactionDirectories(g.layout); err != nil {
		return Journal{}, err
	}
	if err := checkJournalDestination(g.layout.JournalPath, true); err != nil {
		return Journal{}, err
	}
	file, err := os.OpenFile(g.layout.JournalPath, os.O_RDONLY|unix.O_CLOEXEC|unix.O_NOFOLLOW, 0)
	if err != nil {
		if isSymlinkOpenError(err) {
			return Journal{}, ErrUnsafeFile
		}
		if os.IsNotExist(err) {
			return Journal{}, ErrJournalNotFound
		}
		return Journal{}, fmt.Errorf("open transaction journal: %w", err)
	}
	data, readErr := readJournalBytes(file)
	closeErr := file.Close()
	if readErr != nil {
		return Journal{}, readErr
	}
	if closeErr != nil {
		return Journal{}, fmt.Errorf("close transaction journal: %w", closeErr)
	}
	return parseJournal(data)
}

func readJournalBytes(file *os.File) ([]byte, error) {
	info, err := file.Stat()
	if err != nil {
		return nil, fmt.Errorf("stat transaction journal: %w", err)
	}
	if !info.Mode().IsRegular() {
		return nil, ErrUnsafeFile
	}
	if info.Mode().Perm() != 0600 {
		return nil, ErrUnsafePermissions
	}
	if info.Size() > MaxJournalBytes {
		return nil, fmt.Errorf("%w: %w", ErrMalformedJournal, ErrConfigTooLarge)
	}
	data, err := io.ReadAll(io.LimitReader(file, MaxJournalBytes+1))
	if err != nil {
		return nil, fmt.Errorf("read transaction journal: %w", err)
	}
	if len(data) > MaxJournalBytes {
		return nil, fmt.Errorf("%w: %w", ErrMalformedJournal, ErrConfigTooLarge)
	}
	return data, nil
}

var journalFields = map[string]struct{}{
	"format_version": {}, "transaction_id": {}, "phase": {},
	"old_config_hash": {}, "candidate_config_hash": {},
	"old_generation": {}, "candidate_generation": {},
	"service_was_active": {}, "live_config_mode": {},
	"live_config_uid": {}, "live_config_gid": {},
	"candidate_name": {}, "backup_name": {},
}

func parseJournal(data []byte) (Journal, error) {
	fields, err := strictTopLevelObject(data)
	if err != nil {
		return Journal{}, ErrMalformedJournal
	}
	if len(fields) != len(journalFields) {
		return Journal{}, ErrMalformedJournal
	}

	var journal Journal
	if err := unmarshalJournalFields(fields, &journal); err != nil {
		return Journal{}, ErrMalformedJournal
	}
	if err := journal.Validate(); err != nil {
		return Journal{}, err
	}
	return journal, nil
}

func strictTopLevelObject(data []byte) (map[string]json.RawMessage, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	token, err := decoder.Token()
	if err != nil {
		return nil, err
	}
	delim, ok := token.(json.Delim)
	if !ok || delim != '{' {
		return nil, errors.New("journal is not an object")
	}

	fields := make(map[string]json.RawMessage, len(journalFields))
	for decoder.More() {
		keyToken, err := decoder.Token()
		if err != nil {
			return nil, err
		}
		key, ok := keyToken.(string)
		if !ok {
			return nil, errors.New("journal field name is not a string")
		}
		if _, ok := journalFields[key]; !ok {
			return nil, errors.New("unknown journal field")
		}
		if _, duplicate := fields[key]; duplicate {
			return nil, errors.New("duplicate journal field")
		}
		var value json.RawMessage
		if err := decoder.Decode(&value); err != nil {
			return nil, err
		}
		fields[key] = value
	}
	endToken, err := decoder.Token()
	if err != nil {
		return nil, err
	}
	end, ok := endToken.(json.Delim)
	if !ok || end != '}' {
		return nil, errors.New("journal object did not end")
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		return nil, errors.New("journal has trailing JSON")
	}
	return fields, nil
}

func unmarshalJournalFields(fields map[string]json.RawMessage, journal *Journal) error {
	decode := func(name string, destination any) error {
		value, ok := fields[name]
		if !ok {
			return errors.New("missing journal field")
		}
		return json.Unmarshal(value, destination)
	}
	if err := decode("format_version", &journal.FormatVersion); err != nil {
		return err
	}
	if err := decode("transaction_id", &journal.TransactionID); err != nil {
		return err
	}
	if err := decode("phase", &journal.Phase); err != nil {
		return err
	}
	if err := decode("old_config_hash", &journal.OldConfigHash); err != nil {
		return err
	}
	if err := decode("candidate_config_hash", &journal.CandidateConfigHash); err != nil {
		return err
	}
	if err := decode("old_generation", &journal.OldGeneration); err != nil {
		return err
	}
	if err := decode("candidate_generation", &journal.CandidateGeneration); err != nil {
		return err
	}
	if err := decode("service_was_active", &journal.ServiceWasActive); err != nil {
		return err
	}
	if err := decode("live_config_mode", &journal.LiveConfigMode); err != nil {
		return err
	}
	if err := decode("live_config_uid", &journal.LiveConfigUID); err != nil {
		return err
	}
	if err := decode("live_config_gid", &journal.LiveConfigGID); err != nil {
		return err
	}
	if err := decode("candidate_name", &journal.CandidateName); err != nil {
		return err
	}
	return decode("backup_name", &journal.BackupName)
}

func (g *LockGuard) UpdateJournalPhase(phase JournalPhase) error {
	done, err := g.beginOperation()
	if err != nil {
		return err
	}
	defer done()
	journal, err := g.readJournalLocked()
	if err != nil {
		return err
	}
	if phase == PhaseRollbackFailed {
		if journal.Phase != PhasePrepared && journal.Phase != PhaseRollbackFailed {
			return ErrInvalidJournal
		}
	} else if phase != PhasePrepared || journal.Phase != PhasePrepared {
		return ErrInvalidJournal
	}
	journal.Phase = phase
	encoded, err := marshalJournal(journal)
	if err != nil {
		return err
	}
	if err := checkJournalDestination(g.layout.JournalPath, true); err != nil {
		return err
	}
	return g.replaceJournal(encoded, journal.TransactionID)
}

// SetJournalPhase is a descriptive alias for UpdateJournalPhase.
func (g *LockGuard) SetJournalPhase(phase JournalPhase) error {
	return g.UpdateJournalPhase(phase)
}

func (g *LockGuard) replaceJournal(encoded []byte, transactionID string) error {
	tempPath, file, err := g.openJournalTemp(transactionID)
	if err != nil {
		return err
	}
	keepTemp := true
	defer func() {
		if keepTemp {
			_ = os.Remove(tempPath)
		}
	}()
	if err := writeAll(file, encoded); err != nil {
		_ = file.Close()
		return fmt.Errorf("write updated transaction journal: %w", err)
	}
	if err := fsyncAndClose(file); err != nil {
		return fmt.Errorf("sync updated transaction journal: %w", err)
	}
	if err := checkJournalDestination(g.layout.JournalPath, true); err != nil {
		return err
	}
	if err := os.Rename(tempPath, g.layout.JournalPath); err != nil {
		return fmt.Errorf("replace transaction journal: %w", err)
	}
	keepTemp = false
	return fsyncDirectory(g.layout.StateDir)
}

func (g *LockGuard) RemoveJournal() error {
	done, err := g.beginOperation()
	if err != nil {
		return err
	}
	defer done()
	if err := checkJournalDestination(g.layout.JournalPath, true); err != nil {
		return err
	}
	if err := os.Remove(g.layout.JournalPath); err != nil {
		if os.IsNotExist(err) {
			return ErrJournalNotFound
		}
		return fmt.Errorf("remove transaction journal: %w", err)
	}
	if err := fsyncDirectory(g.layout.StateDir); err != nil {
		return fmt.Errorf("sync transaction state directory after journal removal: %w", err)
	}
	return nil
}
